### ISSUE TITLE
Xiaomi Bluetooth WirelessGamecontroller still visible (no exclusive mode) after Win Update.

### ISSUE THREAD

**Issue by XxHansYoloxX** [dancol90/mi-360#13]
The app worked OK till now, but after windows update the Xiaomi Bluetooth Wireless Gamecontroller stays visible in controller settings. 
Some games do not work this way, Sekiro being one.

Please help.

**Comment by dancol90** [comment]
Hi!

Up to the current version (0.4.1) the software doesn't use HID exclusive mode, but it tries to hide the device with a special third-party filter driver (HIDGuardian). This system works fine most of the time but, due to its nature, there may be some configurations where it may not perform as well.

You may try to uninstall and reinstall mi-360 from scratch, to reinstall also the drivers.

Now, HIDGuardian has been marked as deprecated by its creator. I'm about to release a new version of mi-360 that uses HID exclusive mode (the right, non-hacky way of hiding a device), so stay tuned!

**Comment by jlarrainarellano** [comment]
Hi!

Thanks a lot for all your work!
I've just downloaded the latest version (0.5.2) and everything is working fine, but I still can see the Xiaomi Bluetooth Wireless Game Controller in my connected devices

Is there something else that I need to do to fix this?

**Comment by dancol90** [comment]
It seems to be a limitation in Windows 10, see https://github.com/dancol90/mi-360/issues/21#issuecomment-720114648
