### ISSUE TITLE
How to remove all the drivers?

### ISSUE THREAD

**Issue by T3rm1** [dancol90/mi-360#14]
I used the installer. The installer installed several drivers.
I uninstalled the program. All the drivers are still on my system. Why aren't they uninstalled when I uninstall the program?

**Comment by dancol90** [comment]
Hi, the uninstaller should remove the bundled drivers (HidGuardian and ViGEmBus).
If not, it might be due to some permissions issues.
Have you granted the uninstaller UAC permission?

Anyway,  you can remove them manually using `devcon.exe` (you can find it inside the Drivers folder of this repo):

```
devcon.exe remove Root\ViGEmBus

devcon.exe classfilter HIDClass upper !HidGuardian
devcon.exe remove Root\HidGuardian
```

Let me know if it works
